### PR TITLE
Request

### PR DESCRIPTION
**Pull request by SenseiOfficial**
Please allow e pull the repo

### CODE REVIEW

**Comment by pokurt** [comment]
What are you even doing

**Comment by MrCarb0n** [comment]
how old are you? @anan2005

**Comment by code-rgb** [comment]
@anan2005 https://www.amazon.in/1001-Ridiculous-Ways-David-Southwell/dp/1853757969

**Comment by HiddenCrush** [comment]
Dumbass do commit on ur own forked repo

**Comment by pokurt** [comment]
I dont think he even knows how comments on github issues and pr works

**Comment by pokurt** [comment]
This doesnt improve anything. Nana Remix is on 2.1 and this is also breaking builds as you can see on docker hub and CircleCI, hence this pull request will be closed

**Comment by SenseiOfficial** [comment]
> What are you even doing

Sorry for the inconvenience caused , sadly I have one dumbass on the board with my team who has done this ridiculous act . I think I should give him some knowledge of git 😂.

I am very Sorry for this and promise I won't allow him to this further .

**Comment by SenseiOfficial** [comment]
> how old are you? @anan2005

I am 17 years old from Gujarat, India . I am founder and CEO at Xccurate security Inc . , Actually this ridiculous act was done by one of my dumb ass employee  who has a learn a lot about Git and I am very sorry for the problem he caused here .



You can read about me -
~ https://link.medium.com/Xzqcqei4qbb

**Comment by code-rgb** [comment]
k

> > how old are you? @anan2005
> 
> I am 17 years old from Gujarat, India . I am founder and CEO at Xccurate security Inc . , Actually this ridiculous act was done by one of my dumb ass employee who has a learn a lot about Git and I am very sorry for the problem he caused here .
> 
> You can read about me -
> ~ https://link.medium.com/Xzqcqei4qbb

k

**Pull request closed without merging**
