### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by Kyliekyler**
Changelog:
- Fix Sqlalchemy Error

Signed-off-by: Kyliekyler <siosonkylebrandon@gmail.com>

### CODE REVIEW

**Comment by pokurt** [comment]
To fix heroku deploys?

**Comment by Kyliekyler** [comment]
> To fix heroku deploys?

Im using zeet, this is to fix error I sent on support group

https://t.me/nanabotsupport/86960

**Comment by pokurt** [comment]
> > To fix heroku deploys?
> 
> Im using zeet, this is to fix error I sent on support group
> 
> https://t.me/nanabotsupport/86960

oh nice! ill merge this commit. can you change the base or close this pr and move the commit to `translations` branch? ill merge from there into master

**Comment by Kyliekyler** [comment]
Alright

> > > To fix heroku deploys?
> > 
> > 
> > Im using zeet, this is to fix error I sent on support group
> > https://t.me/nanabotsupport/86960
> 
> oh nice! ill merge this commit. can you change the base or close this pr and move the commit to `translations` branch? ill merge from there into master

Alright

**Pull request closed without merging**
